const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../../../../..');
const generated=path.join(root,'Code/Engine/_Module/_AutoGenerated');
const out=path.join(root,'Build/Verification/GrassWind');
fs.mkdirSync(out,{recursive:true});
const cases=[];
for(const name of fs.readdirSync(path.join(generated,'Shaders')).filter(n=>n.endsWith('.cpp'))){
  const text=fs.readFileSync(path.join(generated,'Shaders',name),'utf8');
  const fields=[...text.matchAll(/m_parameterInfo\.emplace_back\( StringID\( "[^"]+" \), StringID\( "([^"]+)" \), (\d+), (\d+) \)/g)];
  if(!fields.length)continue;
  const shader=name.slice(0,-4);
  const reflection=fs.readFileSync(path.join(generated,'ShaderReflection',shader+'.esh'),'utf8');
  const words=reflection.match(/num32BitConstants = (\d+)/);
  const commonOnly=fields.every(f=>['m_shaderIndex','m_shaderFlags','m_opacity','m_reservedESF0'].includes(f[1])||f[1].startsWith('esf_parameter_padding'));
  if(!words&&!commonOnly)throw Error('No packed size for '+shader);
  const expected=words?Number(words[1])*4:32;
  const members=fields.map(f=>`{${f[3]},${f[2]}}`).join(',');
  cases.push(`check(size(std::array<Field,${fields.length}>{{${members}}})==${expected},"generated ${shader} packed size ${expected}");`);
}
if(cases.length<5)throw Error('Too few material layouts; reflection parser may be stale');
fs.writeFileSync(path.join(out,'ShaderParameterLayoutCases.inl'),cases.join('\n')+'\n');
console.log(`Validated fixture generation: ${cases.length} current material layouts`);
function functionBody(file,signature){
  const source=fs.readFileSync(path.join(root,file),'utf8');
  const start=source.indexOf(signature);
  if(start<0)throw Error('Missing function '+signature);
  const brace=source.indexOf('{',start);let depth=0;
  for(let i=brace;i<source.length;i++){
    if(source[i]==='{')depth++;
    if(source[i]==='}'&&--depth===0)return source.slice(start,i+1);
  }
  throw Error('Unclosed function '+signature);
}
const trace=functionBody('Code/Base/Logging/Platform/SystemLog_Win32.cpp','void TraceMessage(');
const log=functionBody('Code/Base/Logging/SystemLog.cpp','void LogAssert(');
fs.writeFileSync(path.join(out,'LogAssertRegression.inl'),trace+'\n'+log+'\n');
