# Read-only, explicit checkpoint selection. Does not stage, modify, or delete files.
param([switch]$Json)
$ErrorActionPreference = 'Stop'
$repo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../../../..'))
$prefix = 'Code/Game/Provenance/'
$selected = [Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
function IncludeFile([string]$relative) {
    $relative = $relative.Replace('\','/')
    $full = Join-Path $repo $relative
    if (-not (Test-Path -LiteralPath $full -PathType Leaf)) { throw "Missing checkpoint input: $relative" }
    [void]$selected.Add($relative)
}
function IncludeTree([string]$relative) {
    foreach ($file in Get-ChildItem -LiteralPath (Join-Path $repo $relative) -Recurse -File) {
        if ($file.FullName -match '[\\/](__pycache__|_AutoGenerated)[\\/]') { continue }
        if ($file.Extension -in @('.exe','.dll','.pdb','.obj','.ilk','.exp','.lib','.pyc','.db','.zip','.blend1','.user')) { continue }
        IncludeFile ([IO.Path]::GetRelativePath($repo,$file.FullName))
    }
}
# Existing integration edits; independent Phase 18 entry and Worldgen evidence stay local.
foreach ($file in (& git -c core.safecrlf=false -C $repo diff --name-only -- Code Esoterica.slnx)) {
    if ($file -eq 'Code/Applications/ProvenanceClient/Main.cpp') { continue }
    IncludeFile $file
}
foreach ($relative in @(
    'Code/Applications/GraniteLab','Code/Applications/ProvenanceVerifier',
    'Code/Game/Provenance/Components','Code/Game/Provenance/Geometry',
    'Code/Game/Provenance/Systems','Code/Game/Provenance/Verification',
    'Data/Provenance',
    # Retain current baked inputs and their export evidence, plus editable source cohorts.
    'Code/Game/Provenance/output/integration',
    'Code/Game/Provenance/output/models/berry_bushes/v001',
    'Code/Game/Provenance/output/models/mushrooms/v001',
    'Code/Game/Provenance/output/models/magical_mushrooms/v001',
    'Code/Game/Provenance/output/models/tools',
    'Code/Game/Provenance/output/placement/world_trees_v002',
    'Code/Game/Provenance/output/imagegen/mud',
    'Code/Game/Provenance/output/imagegen/soil'
)) { IncludeTree $relative }
foreach ($relative in @(
    'GraniteLab.slnx','RunGraniteLab.cmd',
    'Code/Engine/Render/RenderShaderParameterLayout.h',
    'Code/Engine/Render/Shaders/Materials/ProvenanceGraniteTriplanarPBR.esf',
    'Code/Engine/Render/Shaders/Materials/ProvenanceGrassSoilPBR.esf',
    'Code/Engine/Render/Shaders/Materials/ProvenanceGrassWind.esh',
    'Code/Engine/Render/Shaders/Materials/ProvenanceSoilTriplanarPBR.esf',
    'Code/Game/Provenance/output/ASSET_PLACEMENT.md',
    'Code/Game/Provenance/output/models/trees/v002/README.md',
    'Code/Game/Provenance/output/models/trees/v002/manifest.json'
)) { IncludeFile $relative }
$rows = @($selected | Sort-Object | ForEach-Object {
    $file = Get-Item -LiteralPath (Join-Path $repo $_)
    [pscustomobject]@{Path=$_;Bytes=$file.Length}
})
if ($Json) { ConvertTo-Json -InputObject $rows -Depth 3 }
else { $rows.Path }
